[package]
name = "evbunpack-rs"
version = "0.0.2"
edition = "2024"
description = "Enigma Virtual Box unpacker"
license = "Apache-2.0"
authors = ["Vrdons <vrdons@proton.me>"]
readme = "README.md"
exclude = ["target/", ".git/", ".github/", "tests/", "example/", "cliff.toml", "renovate.json"]
repository = "https://github.com/vrdons/evbunpack-rs"

[lib]
name = "evbunpack_rs"
path = "src/lib.rs"

[dependencies]
goblin = { version = "0.10", default-features = false, features = [
    "pe32",
    "std",
] }
thiserror = "2.0"
tracing = "0.1"

[dev-dependencies]
tempfile = "3"

[workspace]
members = ["cli"]

[profile.release-lto]
inherits = "release"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
