[package]
name = "evbunpack-cli"
version = "0.0.2"
edition = "2024"
description = "Command-line binary for evbunpack-rs (Enigma Virtual Box unpacker)"
license = "Apache-2.0"
authors = ["Vrdons <vrdons@proton.me>"]
readme = "README.md"
repository = "https://github.com/vrdons/evbunpack-rs"

[[bin]]
name = "evbunpack"
path = "src/main.rs"

[dependencies]
evbunpack-rs = { path = "..", version = "0.0.2" }

clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"


[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-{ version }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/evbunpack", dest = "/usr/bin/evbunpack", mode = "755" },
]
summary = "Enigma Virtual Box Unpacker"
description = """
Evbunpack is a tool for extracting .enigma1 data from executeable files 
"""
license = "MIT"

[package.metadata.deb]
maintainer = "Vrdons <vrdons@proton.me>"
copyright = "2026, Vrdons <vrdons@proton.me>"
extended-description = """
Evbunpack is a tool for extracting .enigma1 data from executeable files
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    [
        "target/release/evbunpack",
        "usr/bin/",
        "755",
    ],
    [
        "README.md",
        "usr/share/doc/evbunpack/",
        "644",
    ],
]
