[package]
name = "evbunpack-cli"
version = "0.0.1"
edition = "2024"
description = "Command-line binary for evbunpack-rs (Enigma Virtual Box unpacker)"
license = "Apache-2.0"

[[bin]]
name = "evbunpack-rs"
path = "src/main.rs"

[dependencies]
evbunpack-rs = { path = "..", version = "0.2.6" }

clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
